### PR TITLE
Cherry pick for release 0.12 to support KUBECONFIG in OLM

### PR DESCRIPTION
**Pull request by houshengbo**
# Issue to be fixed

## Proposed Changes

* This PR is a cherry-pick of commit 723874e9a1e19ed359e0589b63d7dfa9e388ccde, commit 96b789c7b6ca5d2e47494569e1033249d813a533 and commit dc8dca320dc9066723a7f7d5bf31b43f0bebad31. Additional fixes have been done as well to resolve the conflicts or errors.
* Update the library from jcrossley/manifestival to manifestival/manifestival.

## Release Note

```release-note
```

### CODE REVIEW

**Comment by houshengbo** [comment]
@googlebot I consent

**Comment by houshengbo** [comment]
@googlebot I consent.

**Comment by aliok** [comment]
@googlebot I consent

**Pull request merged**
