### PR TITLE
Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign houshengbo k4leung4
/cc houshengbo k4leung4

### CODE REVIEW

**Comment by trshafer** [comment]
Hey @k4leung4 I'm happy to lgtm but I don't know much about the eventing operator. What kind of review are you looking for me. In general auto update deps should be a pretty quick review. This review looks good because knative.dev/test-infra is the same digest as the serving operator: https://github.com/knative/serving-operator/blob/0b84b5a5a829b4763f95079bc891cbef40d6afc6/Gopkg.lock#L1372

**Comment by k4leung4** [comment]
@trshafer apologies, tagged you in the wrong PR. meant to be on PR #323

**Comment by k4leung4** [comment]
https://github.com/knative/serving-operator/pull/323

**Comment by mattmoor** [comment]
@k4leung4 Is this test known to be failing at head?  seems unrelated.

/retest

**Pull request closed without merging**
