### PR TITLE
Fix image override for jobs

### PR DESCRIPTION
**Pull request by aliok**
Cherry pick https://github.com/knative-sandbox/operator/pull/81

## Release Note

```release-note
Fixed image override for Knative Eventing 0.14 upgrade job
```

### CODE REVIEW

**Comment by aliok** [comment]
@houshengbo

Prow says
```
2020/05/08 09:06:42 Error creating license classifier: cannot register licenses from archive: open /home/prow/go/src/knative.dev/test-infra/vendor/github.com/google/licenseclassifier/licenses/forbidden_licenses.db: no such file or directory\u0026#xA;
```

I see https://github.com/knative/test-infra/pull/1865 and https://github.com/knative/test-infra/pull/1989 and I think we didn't get the change because https://github.com/knative/eventing-operator/pull/208 was closed.

**Comment by houshengbo** [comment]
@aliok Let's only backport to the release-0.14 branch for patch release, since we will no longer maintain the separate operators.

**Pull request closed without merging**
