### PR TITLE
OLM metadata for 0.12.0

### PR DESCRIPTION
**Pull request by aliok**
# Issue to be fixed

Fixes #

## Proposed Changes

* OLM metadata for 0.12.0
* Instructions on how to install the operator with OLM
* .gitignore script scratch dir

## Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by aliok** [comment]
cc @k4leung4 @houshengbo

**Comment by aliok** [comment]
Rebased cc @houshengbo

**Comment by houshengbo** [comment]
@aliok 
0.12.0 of eventing-operator has two CRDs:
https://github.com/knative/eventing-operator/blob/master/config/300-eventing-v1alpha1-knativeeventing-crd.yaml
and
https://github.com/knative/eventing-operator/blob/master/config/300-eventing-v1alpha1-knativeeventing-crd-obsolete.yaml
.
Do we need to add both of them?

**Comment by aliok** [comment]
@houshengbo you're right. I think we need both of them...
I will update the PR.

**Comment by aliok** [comment]
Similar: https://github.com/openshift-knative/serverless-operator/pull/81
I will update similarly

**Comment by aliok** [comment]
Added the old CRD as well now.

**Pull request merged**
